2022-01-06 17:27:13,676 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:27:13,677 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:27:13,677 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:27:13,678 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_172713-14dnmf4h/logs/debug.log
2022-01-06 17:27:13,679 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_172713-14dnmf4h/logs/debug-internal.log
2022-01-06 17:27:13,679 INFO    MainThread:410 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f695c5a54d0>
2022-01-06 17:27:13,680 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:27:13,680 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:27:13,681 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: e3cpeolt
2022-01-06 17:27:13,683 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/e3cpeolt
2022-01-06 17:27:13,688 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:27:13,691 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:27:19,140 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-01-06 17:27:19,241 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:27:19,273 ERROR   MainThread:410 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1971, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1911, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-06 17:29:13,980 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:29:13,981 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:29:13,982 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:29:13,983 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_172913-2fcyy5s7/logs/debug.log
2022-01-06 17:29:13,984 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_172913-2fcyy5s7/logs/debug-internal.log
2022-01-06 17:29:13,984 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:29:13,985 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:29:13,985 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: e3cpeolt
2022-01-06 17:29:13,988 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/e3cpeolt
2022-01-06 17:29:13,994 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 17:29:13,998 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 17:29:14,005 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 17:29:14,015 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 769
2022-01-06 17:29:14,017 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 17:29:14,087 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 17:29:15,379 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 17:29:15,391 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 17:29:15,432 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 17:29:15,432 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 17:29:15,618 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 17:29:18,487 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 17:29:18,493 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 17:29:18,493 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 17:29:18,496 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 17:29:18,496 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 17:29:18,496 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 17:36:07,020 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:36:07,021 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:36:07,022 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:36:07,023 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_173606-1sxj1w86/logs/debug.log
2022-01-06 17:36:07,023 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_173606-1sxj1w86/logs/debug-internal.log
2022-01-06 17:36:07,024 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:36:07,025 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:36:07,025 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 2fcyy5s7
2022-01-06 17:36:07,027 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/2fcyy5s7
2022-01-06 17:36:07,031 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:36:07,032 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:36:07,492 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:36:07,708 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:36:07,933 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 9296
}

2022-01-06 17:36:08,038 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 9296
}

2022-01-06 17:36:08,141 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:08,245 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:08,347 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:08,450 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:08,553 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:09,049 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}

2022-01-06 17:36:09,417 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9296
  total_bytes: 9296
}
local_info {
}

2022-01-06 17:36:10,894 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 17:36:10,907 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 17:36:10,910 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 17:36:10,918 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 17:36:10,926 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 847
2022-01-06 17:36:10,930 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 17:36:10,998 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 17:36:14,436 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 17:36:14,445 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 17:36:14,489 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 17:36:14,489 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 17:36:14,732 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 17:36:17,560 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 17:36:17,563 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 17:36:17,564 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 17:36:17,567 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 17:36:17,568 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 17:36:17,568 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 17:39:29,832 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:39:29,834 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:39:29,834 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:39:29,835 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_173929-2d6zo2b7/logs/debug.log
2022-01-06 17:39:29,835 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_173929-2d6zo2b7/logs/debug-internal.log
2022-01-06 17:39:29,836 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:39:29,837 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:39:29,837 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 1sxj1w86
2022-01-06 17:39:29,840 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/1sxj1w86
2022-01-06 17:39:29,844 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:39:29,846 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:39:30,860 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:39:31,102 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:39:31,771 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 10797
}

2022-01-06 17:39:31,876 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 10797
}

2022-01-06 17:39:31,979 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,081 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,184 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,286 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,389 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,491 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,594 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,696 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,798 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3482
  total_bytes: 10797
}

2022-01-06 17:39:32,901 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:33,005 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:33,107 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:33,210 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:33,312 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:34,108 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}

2022-01-06 17:39:34,460 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10797
  total_bytes: 10797
}
local_info {
}

2022-01-06 17:39:36,189 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 17:39:36,204 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 17:39:36,206 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 17:39:36,214 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 17:39:36,244 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 936
2022-01-06 17:39:36,246 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 17:39:36,304 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 17:39:37,744 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 17:39:37,753 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 17:39:37,796 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 17:39:37,797 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 17:39:37,975 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 17:39:40,765 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 17:39:40,768 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 17:39:40,769 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 17:39:40,774 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 17:39:40,774 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 17:39:40,774 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 17:42:40,924 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 17:42:40,925 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 17:42:40,925 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 17:42:40,926 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_174240-2f2aeqi0/logs/debug.log
2022-01-06 17:42:40,927 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_174240-2f2aeqi0/logs/debug-internal.log
2022-01-06 17:42:40,927 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 17:42:40,928 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 17:42:40,928 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 2d6zo2b7
2022-01-06 17:42:40,931 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/2d6zo2b7
2022-01-06 17:42:40,935 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 17:42:40,936 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 17:42:41,496 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:42:41,742 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 17:42:42,049 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 9312
}

2022-01-06 17:42:42,153 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 9312
}

2022-01-06 17:42:42,255 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:42,358 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:42,461 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:42,563 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:42,665 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:43,234 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}

2022-01-06 17:42:43,589 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9312
  total_bytes: 9312
}
local_info {
}

2022-01-06 17:42:45,048 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 17:42:45,062 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 17:42:45,066 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 17:42:45,073 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 17:42:45,098 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 980
2022-01-06 17:42:45,103 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 17:42:45,154 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 17:42:46,526 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 17:42:46,535 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 17:42:46,578 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 17:42:46,579 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 17:42:46,771 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 17:42:49,493 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 17:42:49,496 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 17:42:49,497 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 17:42:49,502 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 17:42:49,504 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 17:42:49,504 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 18:33:45,430 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 18:33:45,431 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 18:33:45,431 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 18:33:45,432 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_183345-1dxxsqal/logs/debug.log
2022-01-06 18:33:45,433 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_183345-1dxxsqal/logs/debug-internal.log
2022-01-06 18:33:45,433 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 18:33:45,434 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 18:33:45,435 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 2f2aeqi0
2022-01-06 18:33:45,439 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/2f2aeqi0
2022-01-06 18:33:45,442 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 18:33:45,453 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 18:33:45,559 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 18:33:45,676 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 18:33:45,885 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 18:33:46,554 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 195169
}

2022-01-06 18:33:46,660 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 195169
}

2022-01-06 18:33:46,764 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:46,869 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:46,972 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:47,074 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:47,177 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:47,280 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:47,383 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:48,457 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}

2022-01-06 18:33:48,821 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 195169
  total_bytes: 195169
}
local_info {
}

2022-01-06 18:33:50,313 INFO    MainThread:410 [wandb_run.py:_append_history():2130] rendering history
2022-01-06 18:33:50,313 INFO    MainThread:410 [wandb_run.py:_append_summary():2085] rendering summary
2022-01-06 18:33:50,314 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 18:33:50,328 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 18:33:50,333 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 18:33:50,343 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 18:33:50,381 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 1418
2022-01-06 18:33:50,383 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 18:33:50,442 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 18:33:51,836 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 18:33:51,844 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 18:33:51,892 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 18:33:51,894 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 18:33:52,130 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 18:33:55,000 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 18:33:55,005 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 18:33:55,006 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 18:33:55,007 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 18:33:55,008 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 18:33:55,008 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 19:18:49,462 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting env: {}
2022-01-06 19:18:49,464 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-06 19:18:49,464 INFO    MainThread:410 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-06 19:18:49,465 INFO    MainThread:410 [wandb_init.py:_log_setup():371] Logging user logs to w_andb/wandb/run-20220106_191849-39cx6whk/logs/debug.log
2022-01-06 19:18:49,466 INFO    MainThread:410 [wandb_init.py:_log_setup():372] Logging internal logs to w_andb/wandb/run-20220106_191849-39cx6whk/logs/debug-internal.log
2022-01-06 19:18:49,466 INFO    MainThread:410 [wandb_init.py:init():404] calling init triggers
2022-01-06 19:18:49,467 INFO    MainThread:410 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'resize': 0.25, 'batch_size': 8, 'viz_epoch': 10, 'learning_rate': 0.0001, 'num_epochs': 300, 'encoder_channels': [32, 32, 64, 64, 64], 'decoder_channels': [64, 64, 64, 32, 32], 'waypoints': [14, 29], 'temperature': 1.8, 'segmentation_model_fp': 'segmentation_models/SDD_segmentation.pth', 'semantic_classes': 6, 'loss_scale': 1000, 'kernlen': 31, 'nsig': 4, 'use_features_only': False, 'unfreeze': 100, 'use_TTST': True, 'rel_threshold': 0.002, 'use_CWS': True, 'CWS_params': {'sigma_factor': 6, 'ratio': 2, 'rot': True}}
2022-01-06 19:18:49,467 INFO    MainThread:410 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 1dxxsqal
2022-01-06 19:18:49,470 INFO    MainThread:410 [wandb_run.py:finish():1457] finishing run pradipto611/ynet/1dxxsqal
2022-01-06 19:18:49,474 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 19:18:49,483 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 19:18:50,136 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:18:50,254 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:18:50,429 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:18:50,902 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 193710
}

2022-01-06 19:18:51,007 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 193710
}

2022-01-06 19:18:51,109 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18557
  total_bytes: 193710
}

2022-01-06 19:18:51,212 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,317 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,419 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,522 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,625 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,727 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:51,830 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:52,959 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}

2022-01-06 19:18:53,310 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 193710
  total_bytes: 193710
}
local_info {
}

2022-01-06 19:18:54,797 INFO    MainThread:410 [wandb_run.py:_append_history():2130] rendering history
2022-01-06 19:18:54,798 INFO    MainThread:410 [wandb_run.py:_append_summary():2085] rendering summary
2022-01-06 19:18:54,799 INFO    MainThread:410 [wandb_run.py:_append_files():2180] logging synced files
2022-01-06 19:18:54,814 INFO    MainThread:410 [wandb_init.py:init():460] starting backend
2022-01-06 19:18:54,818 INFO    MainThread:410 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-06 19:18:54,825 INFO    MainThread:410 [backend.py:ensure_launched():216] starting backend process...
2022-01-06 19:18:54,867 INFO    MainThread:410 [backend.py:ensure_launched():222] started backend process with pid: 1725
2022-01-06 19:18:54,869 INFO    MainThread:410 [wandb_init.py:init():469] backend started and connected
2022-01-06 19:18:54,928 INFO    MainThread:410 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-06 19:18:56,481 INFO    MainThread:410 [wandb_init.py:init():533] updated telemetry
2022-01-06 19:18:56,489 INFO    MainThread:410 [wandb_init.py:init():563] communicating current version
2022-01-06 19:18:56,533 INFO    MainThread:410 [wandb_init.py:init():568] got version response 
2022-01-06 19:18:56,534 INFO    MainThread:410 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-06 19:18:56,717 INFO    MainThread:410 [wandb_init.py:init():606] starting run threads in backend
2022-01-06 19:18:59,499 INFO    MainThread:410 [wandb_run.py:_console_start():1810] atexit reg
2022-01-06 19:18:59,503 INFO    MainThread:410 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-06 19:18:59,504 INFO    MainThread:410 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-06 19:18:59,508 INFO    MainThread:410 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-06 19:18:59,508 INFO    MainThread:410 [wandb_init.py:init():633] run started, returning control to user process
2022-01-06 19:18:59,508 INFO    MainThread:410 [wandb_watch.py:watch():43] Watching
2022-01-06 19:50:08,100 INFO    MainThread:410 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-06 19:50:08,110 INFO    MainThread:410 [wandb_run.py:_restore():1752] restore
2022-01-06 19:50:09,110 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:50:09,240 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:50:09,412 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 671
}

2022-01-06 19:50:09,625 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 187481
}

2022-01-06 19:50:09,730 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 671
  total_bytes: 188552
}

2022-01-06 19:50:09,833 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:09,938 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:10,040 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:10,143 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:10,245 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:10,348 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:10,450 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:11,686 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}

2022-01-06 19:50:12,039 INFO    MainThread:410 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 188552
  total_bytes: 188552
}
local_info {
}

